services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    image: ollama/ollama:latest
    ports:
    - 11434:11434
    restart: unless-stopped
    volumes:
    - ollama_data:/root/.ollama
volumes:
  ollama_data: {}
