services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - stirling_data:/usr/share/tessdata
    - stirling_configs:/configs
volumes:
  stirling_configs: null
  stirling_data: null
