// Generated by scripts/generate-api-contract.mjs; do not edit.
export const API_V1_ENVELOPE_CONTRACT_SOURCE_SHA256 = '5ffda48b83fd0e59cb57fec35f949dc0402c66ca2728f039c3988608eeb745ac' as const
export const API_V1_ENVELOPE_CONTRACT = {
  "contract": "voidtower.api.envelopes",
  "api_version": "1",
  "envelopes": {
    "plan_success_v1": {
      "schema_version": 1,
      "resource_id": "resource-1",
      "action": "container.start",
      "plan": {
        "job_id": "job-1"
      }
    },
    "job_success_v1": {
      "schema_version": 1,
      "resource_id": "resource-1",
      "action": "container.start",
      "job": {
        "id": "job-1"
      }
    },
    "job_read_v1": {
      "schema_version": 1,
      "resource_id": "resource-1",
      "action": "container.start",
      "job": {
        "id": "job-1"
      }
    },
    "error_v1": {
      "error": {
        "code": "job_not_found",
        "message": "The requested job does not exist."
      }
    }
  }
} as const
