// Generated by scripts/generate-api-contract.mjs; do not edit.
export const API_V1_ENVELOPE_CONTRACT_SOURCE_SHA256 = '014ff86b4164efd3cdbba091dd7cfda95b485a712147b30aa3504e98ef1905ba' as const
export const API_V1_ENVELOPE_CONTRACT = {
  "contract": "voidtower.api.envelopes",
  "api_version": "1",
  "envelopes": {
    "plan_success_v1": {
      "schema_version": 1,
      "resource_id": "resource-1",
      "action": "container.start",
      "plan": {
        "job_id": "job-1"
      }
    },
    "job_success_v1": {
      "schema_version": 1,
      "resource_id": "resource-1",
      "action": "container.start",
      "job": {
        "id": "job-1"
      }
    },
    "job_read_v1": {
      "schema_version": 1,
      "resource_id": "resource-1",
      "action": "container.start",
      "job": {
        "id": "job-1"
      }
    },
    "error_v1": {
      "error": {
        "code": "job_not_found",
        "message": "The requested job does not exist."
      }
    },
    "event_v1": {
      "sequence": 1,
      "event_id": "event-1",
      "schema_version": 1,
      "event_type": "job.running.v1",
      "occurred_at": 100,
      "actor": null,
      "resource_id": "resource-1",
      "job_id": "job-1",
      "approval_id": null,
      "correlation_id": "correlation-1",
      "causation_id": null,
      "payload": {}
    },
    "stream_ready_v1": {
      "cursor": 0,
      "high_water": 0
    },
    "stream_gap_v1": {
      "reason": "behind_retention",
      "requested_after": 0,
      "earliest_available": 1,
      "latest_available": 1
    }
  }
} as const
